[build]
  command = "npm run build"
  publish = ".next"

[[edge_functions]]
  path = "/socketio"
  function = "socketio"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/edge-functions/socketio"
  to = "/socketio"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200

[dev]
  framework = "next"
  targetPort = 3000

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Socket.IO routes first
[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/edge-functions/socketio"
  status = 200
  force = true

# Handle Next.js static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true
  conditions = {Path = "/_next/static/**"}

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true" 