[build]
  command = "npm run build"
  publish = ".next"

[[edge_functions]]
  pattern = "/.netlify/edge-functions/socketio"
  function = "socketio"

[functions]
  included_files = [".next/server/**", ".next/standalone/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle WebSocket connections
[[redirects]]
  from = "/.netlify/edge-functions/socketio"
  to = "/.netlify/edge-functions/socketio"
  status = 200
  force = true

# Handle Next.js static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Handle Next.js data files
[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

# Handle dynamic routes
[[redirects]]
  from = "/room/*"
  to = "/.netlify/functions/server"
  status = 200

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Private-Network = "true"

[[headers]]
  for = "/.netlify/edge-functions/socketio"
  [headers.values]
    Content-Type = "text/plain"
    Upgrade = "websocket"
    Connection = "Upgrade"
    Sec-WebSocket-Version = "13"
    Sec-WebSocket-Protocol = "websocket"

[dev]
  framework = "next"
  targetPort = 3000

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9" 